---
- name: Disable port
  become: yes
  hosts: all
  vars_files:
    - /etc/ansible/ansible-playbooks/firewall/vars/port.yml
  tasks:
    - name: Disable "{{ item.port }}"
      firewalld:
        port:
          - "{{ item.port }}"
        permanent: yes
        state: disabled

      when:
        - ansible_facts['distribution'] =="CentOS"

      loop: "{{ ports }}"