---
- name: Get directory list
  hosts: all
  gather_facts: false
  vars_files:
    - /etc/ansible/vars/test_path.yml

  tasks:
    - name: Ordered list of "{{ path }}"
      raw: ls -la "{{ path }}"
      register: print_output

    - debug: var=print_output.stdout_lines
